export const PATH = {
  ADMIN_DASHBOARD: 'AdminDashboardScreen',
  ADMIN_VOTE_EDIT: 'AdminVoteEditScreen',
  ADMIN_VOTE_RESULT: 'AdminVoteResultScreen',
  ADMIN_VOTE_STATUS: 'AdminVoteStatusScreen',
  ADMIN_HOME: 'AdminHomeScreen',
  HOME: 'HomeScreen',
  LOGIN: 'LoginScreen',
  NOTICE: 'NoticeScreen',
  NOTICE_CONTENT: 'NoticeContentScreen',
  VOTE: 'VoteScreen',
  VOTE_COMPLETE: 'VoteCompleteScreen',
  VOTE_CREATE: 'VoteCreateScreen',
  VOTE_CREATE_COMPLETE: 'VoteCreateCompleteScreen',
  VOTE_PROMISE: 'VotePromiseScreen',
  VOTE_RESULT: 'VoteResultScreen',
  VOTE_RESULT_CONTENT: 'VoteResultContentScreen',
} as const;
